---
# pyspelling configuration file
# https://facelessuser.github.io/pyspelling/configuration/
matrix:
  - name: Python Source
    aspell:
      lang: en
      d: en_AU
      ignore-case: true
    sources:
      - content/posts/*.md
      dictionary:
          wordlists:
            - spelllist.txt
