---
name: Deploy Static Website

on:  # yamllint disable rule:truthy
    push:
        branches:
            - master
            - feature/gh-actions

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Install Hugo
              run: |
                  HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
                  wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
                  tar xvzf ${HUGO_DOWNLOAD} hugo
                  mv hugo $HOME/hugo
              env:
                  HUGO_VERSION: 0.71.0
            - name: Build Website
              run: $HOME/hugo -v
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_S3_BUCKET_REGION }}
            - name: Copy blog files to s3 bucket
              run: |
                  aws s3 sync --acl "public-read" public/ ${{ secrets.AWS_S3_BUCKET }}
            - name: Update Google sitemap
              run: |
                  curl --silent ${{ secrets.SITEMAP_URL }}
            - name: Invalidate Cloudfront cache
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"
