---
name: Spellcheck Website

on:  # yamllint disable rule:truthy
    push:
        branches:
            - feature/*
    pull_request:
        branches:
            - master

jobs:
    build:
        name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.18.0
        with:
            config_path: pyspelling.yml
