---
name: Vale - Spelling and Grammar
on:  # yamllint disable rule:truthy
    push:
        branches:
            - feature/*
    pull_request:
        branches:
            - master

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.4.3
      with:
        # Optional
        # config: .vale.ini

        # Optional
        files: content/
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}