---
name: Vale - Editorial Review
on: # yamllint disable rule:truthy
  push:
    branches:
      - feature/*

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Vale - Editorial Review
        # uses: errata-ai/vale-action@v2.0.1
        uses: errata-ai/vale-action@reviewdog

        with:
          # Use Vale, write-good, Microsoft, Readability and Google styles for editorial style review.
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            https://github.com/errata-ai/Readability/releases/latest/download/Readability.zip
          files: content/
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
