---
name: Vale - Editorial Review
on: # yamllint disable rule:truthy
  push:
    branches:
      - feature/*

jobs:
  prose:
    name: Perform editorial review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Vale - Editorial Review
        # uses: errata-ai/vale-action@v2.0.1
        uses: errata-ai/vale-action@reviewdog

        with:
          files: content/
          fail_on_error: true
          reporter: github-pr-review
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
